services:

  boneyard:
    build: .
    command:
      - /app/bin/server
    ports:
      - 4000:4000
    environment:
      - FLY_APP_NAME=boneyard
      - FLY_IMAGE_REF=ref
      - FLY_PRIVATE_IP=127.0.0.1
      - PORT=4000
      # - PHX_HOST=boneyard.docker.localhost
      - SECRET_KEY_BASE=0ifHan15bsgGLfSEeHB21ifI7c/qdQ32iUTHfPbaI7lRZ9DZ8ZBidEamarRcoSt/l
      # - DNS_CLUSTER_QUERY=boneyard.docker.internal
